### ISSUE TITLE
UserUpdated activity event contains group info

### ISSUE THREAD

**Issue by ryanjohndias** [kin-business/kin.api.public#42]
Thus, the group image gets shown, due to the current image rules

Snippet of the activity item:
```
        {
          "event": "UserUpdated",
          "group": {
            "name": "First group",
            "image": "http://assets.dev.kin.business.s3.amazonaws.com/groups/5d77972899e6780002273062/5d77972899e6780002273062-primary.jpg?uid=66bf38e0-6e1f-4414-b45d-92d9440c33c4"
          },
          "byUser": {
            "id": "5d779702dc2113a2f68df53d",
            "name": "Ryan",
            "image": "http://assets.dev.kin.business.s3.amazonaws.com/users/5d779702dc2113a2f68df53d/5d779702dc2113a2f68df53d-primary.jpg?uid=899dc0c5-fc8e-4acf-8a58-dac9d0725954"
          },
          "message": "You changed your name to Ryan."
        },
```

**Comment by rolfwessels** [comment]
We will change this to not relate to a group 👍

**Comment by rolfwessels** [comment]
Should now be resolved. Please close when tested.

**Comment by ryanjohndias** [comment]
Still happening, as seen in screenshot of https://github.com/kin-business/kin.api.public/issues/44 (group image shown)

**Comment by ryanjohndias** [comment]
Thanks
