### ISSUE TITLE
Changing your user's name results in an activity item for each group you're part of

### ISSUE THREAD

**Issue by ryanjohndias** [kin-business/kin.api.public#44]
![Screenshot 2019-09-11 at 09 52 56](https://user-images.githubusercontent.com/6240969/64678513-05357980-d47a-11e9-80c9-23924a53bf46.png)

**Comment by rolfwessels** [comment]
Yup this will change 👍 Will comment here when it is ready.

**Comment by rolfwessels** [comment]
Should now be resolved. Please close when tested.

**Comment by ryanjohndias** [comment]
Still happening:

![Screenshot 2019-09-12 at 08 48 34](https://user-images.githubusercontent.com/6240969/64760496-2198eb00-d53a-11e9-9cfb-287766f3b991.png)

**Comment by rolfwessels** [comment]
Should be there now

**Comment by ryanjohndias** [comment]
Fixed, thanks
